modules:
  - "me.hope.lpt.module.VehiclePrevent"
  - "me.hope.lpt.module.AchievementListener"
  - "me.hope.lpt.module.DreamFishLimiter"
  - "me.hope.lpt.module.WardrobeMender"
  - "me.hope.lpt.module.TeleportBlackList"